// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.3
// LVGL version: 8.3.6
// Project name: handwritten_bismillah

#ifndef _HANDWRITTEN_BISMILLAH_UI_H
#define _HANDWRITTEN_BISMILLAH_UI_H

#ifdef __cplusplus
extern "C" {
#endif

    #include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"
void titleSlide_Animation( lv_obj_t *TargetObject, int delay);
void panelSlide_Animation( lv_obj_t *TargetObject, int delay);
void slideSettings_Animation( lv_obj_t *TargetObject, int delay);
void slideSettingsClose_Animation( lv_obj_t *TargetObject, int delay);
void predictSlide_Animation( lv_obj_t *TargetObject, int delay);
void predictSlideOut_Animation( lv_obj_t *TargetObject, int delay);
void titleAnim1_Animation( lv_obj_t *TargetObject, int delay);
void titleAnim2_Animation( lv_obj_t *TargetObject, int delay);
// SCREEN: ui_TitleScreen
void ui_TitleScreen_screen_init(void);
extern lv_obj_t *ui_TitleScreen;
extern lv_obj_t *ui_PanelProfile;
extern lv_obj_t *ui_myNIM;
extern lv_obj_t *ui_Image2;
extern lv_obj_t *ui_myName;
extern lv_obj_t *ui_PanelProj;
extern lv_obj_t *ui_nameProj;
// SCREEN: ui_ScreenMain
void ui_ScreenMain_screen_init(void);
extern lv_obj_t *ui_ScreenMain;
extern lv_obj_t *ui_Title;
extern lv_obj_t *ui_MainPanel;
void ui_event_predictButton( lv_event_t * e);
extern lv_obj_t *ui_predictButton;
extern lv_obj_t *ui_Label3;
extern lv_obj_t *ui_delButton;
extern lv_obj_t *ui_Label2;
void ui_event_settingsButton( lv_event_t * e);
extern lv_obj_t *ui_settingsButton;
extern lv_obj_t *ui_Label4;
extern lv_obj_t *ui_setting;
void ui_event_Arc1( lv_event_t * e);
extern lv_obj_t *ui_Arc1;
extern lv_obj_t *ui_Label1;
void ui_event_applyButton( lv_event_t * e);
extern lv_obj_t *ui_applyButton;
extern lv_obj_t *ui_Label7;
extern lv_obj_t *ui_lineLabel;
extern lv_obj_t *ui_Label6;
extern lv_obj_t *ui_colorSw;
extern lv_obj_t *ui_predictPanel;
extern lv_obj_t *ui_Image1;
extern lv_obj_t *ui_namePredict;
extern lv_obj_t *ui_Roller2;
extern lv_obj_t *ui_Arc2;
extern lv_obj_t *ui_nameProb;
extern lv_obj_t *ui_label1;
extern lv_obj_t *ui_timeNN;
void ui_event_backButton( lv_event_t * e);
extern lv_obj_t *ui_backButton;
extern lv_obj_t *ui_Label5;
extern lv_obj_t *ui_percentPredict;
void ui_event____initial_actions0( lv_event_t * e);
extern lv_obj_t *ui____initial_actions0;

LV_IMG_DECLARE( ui_img_dteti_png);   // assets/dteti.png
LV_IMG_DECLARE( ui_img_path1_png);   // assets/path1.png
LV_IMG_DECLARE( ui_img_roller_bg_png);   // assets/roller_bg.png



void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
